### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by kreezxil** [cyanobacterium/ElectricAdvantage#1]
I've been intrigued since discovering this in your repositories, watching it almost since you started it. What's the status of it?

**Comment by DrPlantabyte** [comment]
I'm almost done with the JSON files and textures, then all I'll have to do is implement the code (which generally takes me less time than textures). After that, I'll have to translate the block and item names into German, Italian, Portuguese, Spanish, Japanese, and Chinese. And then I'll have to take screenshots and make a forum post about it (that task by itself takes a whole afternoon, not to mention making the Wiki pages).

So as of right now, I think I'll have beta version 0.1 ready in about a week from today (v0.1 will just contain the steam-powered and solar-powered electric generators and maybe the arc furnace). It'll be 2-4 weeks after that before version 1.0 is ready. I promise it will be well worth the wait.

**Comment by kreezxil** [comment]
Wow! Do you speak all of those languages? (that's my take away) :)

**Comment by DrPlantabyte** [comment]
Nah, I only speak 'Merican and German. I use google translate for the rest and hope for the best.

**Comment by kreezxil** [comment]
Google Translate for teh Win! :) I've used it communicate with others around the world.
