### ISSUE TITLE
Powdered sulfur powder (Mineralogy vs. EA)

### ISSUE THREAD

**Issue by 7eggert** [cyanobacterium/ElectricAdvantage#10]
Electric Advantage and Mineralogy both have sulfur ore. One gives sulfur powder, one gives powdered sulfur.

**Comment by DrPlantabyte** [comment]
Both are essentially the same item (should be equivalent thanks to the ore dictionary) and functionally those are the same name. Just set the spawn rate for one of them to 0 so only the one you like better will appear in the world.

**Comment by 7eggert** [comment]
Then one of the ore dict entries is b0rken. You can change one into the other but not back.

**Comment by DrPlantabyte** [comment]
Well I'd better fix that then. How are you converting from one to another?

EDIT: It looks like the fundamental problem is that English has multiple spellings for S: "sulfur" and "sulphur" (in occasionally "sulphre"). Mineralogy only uses sulfur while Electric Advantage registers several spellings in the ore dictionary.

**Comment by DrPlantabyte** [comment]
Does the latest version of Minecraft Mineralogy fix this problem?

**Comment by 7eggert** [comment]
I'm still using 1.9.0, will take some time to test

**Comment by jriwanek** [comment]
Closing due to lack of response
