### ISSUE TITLE
New Bug?

### ISSUE THREAD

**Issue by Nijoma69** [cyanobacterium/ElectricAdvantage#2]
Hi,

Think I might have stumbled across a small bug, just had 3x consecutive crashes to desktop after using various seeds from the MasterChef Mod (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2346438-1-7-x-1-8-x-master-chef-mod-more-than-just-food) with the ElectricalAdvantage Growth Chambers (using Hopper Ducts to pull from Growth Chamber output inventories).

Each was a hard crash to desktop ("Ticking Block Entity:Null Pointer Exception"), the world can be reloaded but CTD's with same error within 10 seconds of loading.

MC crash logs attached:-

[crash-2016-01-02_20.11.46-server.txt](https://github.com/cyanobacterium/ElectricAdvantage/files/76387/crash-2016-01-02_20.11.46-server.txt)
[crash-2016-01-02_20.05.43-server.txt](https://github.com/cyanobacterium/ElectricAdvantage/files/76386/crash-2016-01-02_20.05.43-server.txt)
[crash-2016-01-02_20.02.25-server.txt](https://github.com/cyanobacterium/ElectricAdvantage/files/76385/crash-2016-01-02_20.02.25-server.txt)

Regards
N.

**Comment by Nijoma69** [comment]
Update:

Removed Hopper Ducts and replaced with conveyors to pull items from output slots, crash still happens.

Tested with all MasterChef Mod seeds ... crashes as growth reaches 100% and output slots are about to be populated.

Vanilla food items appear to be OK

N.

**Comment by DrPlantabyte** [comment]
Sorry for the long delay. I'll look into it now.

Update: The MasterChef seeds seem to cause a crash when asked for their maximum stack size, but it could still be an issue with my growth algorithm.

Another update: ~~after I updated to the latest recommended forge, growth chambers are not working at all. I'll fix that now.~~ I was using coarse dirt instead of regular dirt. I did successfully recreate your crash, so now I can debug it.

**Comment by DrPlantabyte** [comment]
I've discovered that the MasterChef plant blocks have invalid item stacks in their loot drops, which is what is causing the crash. I should be able to detect and avoid these invalid stacks.

**Comment by DrPlantabyte** [comment]
Now fixed in version 1.0.5 (will be released soon).

**Comment by Nijoma69** [comment]
Fantastic, glad I was able to help you refine an excellent mod
