### ISSUE TITLE
Also not an issue

### ISSUE THREAD

**Issue by brisingraerowing** [cyanobacterium/ElectricAdvantage#4]
How is the port to 1.8.9 going? I am missing the super cool LED bars.

**Comment by brisingraerowing** [comment]
@cyanobacterium Any news? Are you doing OK?

**Comment by DrPlantabyte** [comment]
https://github.com/cyanobacterium/PowerAdvantageAPI/releases/tag/v1.4.4
https://github.com/cyanobacterium/SteamAdvantage/releases/tag/v1.5.1
https://github.com/cyanobacterium/ElectricAdvantage/releases/tag/v1.1.0
