### ISSUE TITLE
Incompatibility with rf power

### ISSUE THREAD

**Issue by ghost** [cyanobacterium/ElectricAdvantage#5]
We could not get a rockcrusher to accept any of the rf power generators or pipes we have, if this is by design please consider a conversion block, rf power is pretty much the main power method in Minecraft, to create two types of power generation and run two types of cables is a bit crazy. But to convert between the two (yours to rf and rf to yours) would give players choice and keep it comparable with the tons of rf power using/generating mods out there

I'm hoping it's just a bug though.
Latest version of everything as of 2 hours ago
Forge 1756
Mc 1.8.9

**Comment by DrPlantabyte** [comment]
Not a bug. There is a conversion block for exactly that purpose (added in a recent update). It's called the Steam-RF Transformer or Electricity-RF Transformer (depending on which energy you want to use).

If RF had been immediately ported to Minecraft 1.8.0, I might have used it, but Power Advantage was completed while the RF fans were still petitioning to boycott Minecraft 1.8 entirely. In the absence of any tech mods at all, I invented a system from the ground-up to be optimized for Minecraft 1.8.

**Comment by ghost** [comment]
Cool will update once home from work, no insult was ment and I apologise if one was taken.

**Comment by DrPlantabyte** [comment]
Sorry for the rant. I never liked RF much even before it became the standard in Minecraft 1.7.2 and literally had people telling me to stop making mods when I started working on the ground-work for Power Advantage in the early days of Minecraft 1.8
