### ISSUE TITLE
Null pointer exception when interacting with Automated Assembler

### ISSUE THREAD

**Issue by dreness** [cyanobacterium/ElectricAdvantage#6]
[crash-2016-03-20_01.57.40-server.txt](https://github.com/cyanobacterium/ElectricAdvantage/files/181220/crash-2016-03-20_01.57.40-server.txt)

I was experimenting with the Automated Assembler and hit this crash, which unfortunately is repeatable, and has rendered my (multiplayer) world inoperable. The crash happened immediately after clicking an item stack in either the input or output of the Assembler. I may have had items on the cursor at the time (i.e. being placed into the slot I clicked), and the item I was placing might not have matched what was already there. The machine was running, being fed from a crusher --> conveyor.

Any tips for manually fixing the bad state?

The crashing line is:

`itemStack = itemStack.copy();`

I'm not sure how doCraft() hands a null item to insertItemToOutputSlots (probably just 'winning' a race), but that's what it looks like to me. Perhaps checking itemStack for null at [the top of insertItemToOutputSlots in ElectricMachineTileEntity](https://github.com/cyanobacterium/ElectricAdvantage/blob/a9414b8ec6c33cbdf6e4e0548f9f02f6151a9df5/src/main/java/cyano/electricadvantage/machines/ElectricMachineTileEntity.java#L300) is in order?

In any case, I'm very much enjoying Power/Electric/Steam Advantage! This is the first real problem I've encountered after about a month of use.

**Comment by DrPlantabyte** [comment]
I think you're right. The assembler has a state machine and I think that you just got really unlucky and added an item in the game tick after it finished its crafting but before it created the resulting item.

This should be an easy fix, but I'm in the process of migrating my dev environment to a new computer, so who knows how long it will take me to get everything setup for mod-making.

**Comment by DrPlantabyte** [comment]
Should now be fixed in version 1.1.2
https://github.com/cyanobacterium/ElectricAdvantage/releases/tag/v1.1.2
